In [1]:
#importing relevant python libraries

import nltk
nltk.download('wordnet')
from nltk import sent_tokenize, word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer

import numpy as np
import pandas as pd

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
#Loading the tags csv file into a dataframe
tags = pd.read_csv('tags.csv')
tags

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [3]:
#Taking all the tags and creating a list
tag_list = list(tags['tag'])
len(tag_list)

3683

In [4]:
#converting all the tags into lower case 
for i in range(len(tag_list)):
    tag_list[i] = tag_list[i].lower()
tag_list

['funny',
 'highly quotable',
 'will ferrell',
 'boxing story',
 'mma',
 'tom hardy',
 'drugs',
 'leonardo dicaprio',
 'martin scorsese',
 'way too long',
 'al pacino',
 'gangster',
 'mafia',
 'al pacino',
 'mafia',
 'holocaust',
 'true story',
 'twist ending',
 'anthony hopkins',
 'courtroom drama',
 'twist ending',
 'britpop',
 'indie record label',
 'music',
 'dumpster diving',
 'sustainability',
 'romantic comedy',
 'wedding',
 'painter',
 'bloody',
 'black hole',
 'sci-fi',
 'time-travel',
 'fantasy',
 'magic board game',
 'robin williams',
 'beautiful scenery',
 'epic',
 'historical',
 'inspirational',
 'medieval',
 'mel gibson',
 'oscar (best cinematography)',
 'revenge',
 'sword fight',
 'black comedy',
 'christina ricci',
 'christopher lloyd',
 'dark comedy',
 'family',
 'gothic',
 'al pacino',
 'andy garcia',
 'classic',
 'francis ford coppola',
 'mafia',
 'black comedy',
 'christina ricci',
 'christopher lloyd',
 'family',
 'gothic',
 'quirky',
 'family',
 'funny',
 'macaulay culkin',
 'sequel',
 'animation',
 'disney',
 'funny',
 'original',
 'pixar',
 'sequel',
 'tom hanks',
 'ancient rome',
 'epic',
 'history',
 'imdb top 250',
 'revenge',
 'rome',
 'russell crowe',
 'ed harris',
 'jude law',
 'rachel weisz',
 'sniper',
 'world war ii',
 'al pacino',
 'atmospheric',
 'hilary swank',
 'robin williams',
 'sequel',
 'violent',
 'dogs',
 'eric bana',
 'mad scientist',
 'marvel',
 'captain nemo',
 'comic book',
 'gothic',
 'peta wilson',
 'sean connery',
 'superhero',
 'adventure',
 'angelina jolie',
 'heroine in tight suit',
 'adventure',
 'ensemble cast',
 'fantasy',
 'fantasy world',
 'great soundtrack',
 'lord of the rings',
 'scenic',
 'stylized',
 'tolkien',
 'hilarious',
 'steve carell',
 'will ferrell',
 'animation',
 'anime',
 'cyberpunk',
 'dark',
 'matrix',
 'sci-fi',
 'dark comedy',
 'jim carrey',
 'meryl streep',
 'quirky',
 'stylized',
 'adam sandler',
 'family',
 'sweet',
 'british gangster',
 'confusing',
 'daniel craig',
 'exquisite plotting.',
 'organized crime',
 'stylish',
 'tom hardy',
 'anime',
 'fantasy world',
 'hayao miyazaki',
 'studio ghibli',
 'david thewlis',
 'eva green',
 'liam neeson',
 'orlando bloom',
 'chris evans',
 'comic book',
 'heroine in tight suit',
 'jessica alba',
 'sexy female scientist',
 'superhero',
 'gothic',
 'helena bonham carter',
 'johnny depp',
 'tim burton',
 'visually appealing',
 'black comedy',
 'clever',
 'fast-paced dialogue',
 'good dialogue',
 'robert downey jr.',
 'witty',
 'adventure',
 'audrey tautou',
 'conspiracy theory',
 'mystery',
 'paris',
 'tom hanks',
 'treasure hunt',
 'brad pitt',
 'cate blanchett',
 'multiple storylines',
 'social commentary',
 'ben stiller',
 'robin williams',
 'emma thompson',
 'maggie gyllenhaal',
 'modern fantasy',
 'romance',
 'surreal',
 'will ferrell',
 'marion cotillard',
 'africa',
 'corruption',
 'jennifer connelly',
 'justice',
 'leonardo dicaprio',
 'bad acting',
 'bad jokes',
 'bad plot',
 'chris evans',
 'jessica alba',
 'marvel',
 'sexy female scientist',
 'rachel weisz',
 'ryan reynolds',
 'fantasy',
 'lion',
 'narnia',
 'tilda swinton',
 'bad script',
 'charlize theron',
 'will smith',
 'anne hathaway',
 'steve carell',
 'comedy',
 'funny',
 'will ferrell',
 'comedy',
 'james franco',
 'seth rogen',
 'stoner movie',
 'audience intelligence underestimated',
 'boring',
 'chick flick',
 'overrated',
 'teen movie',
 'adrien brody',
 'con artists',
 'funny',
 'interesting characters',
 'mark ruffalo',
 'rachel weisz',
 'bill murray',
 'dark comedy',
 'emma stone',
 'funny',
 'jesse eisenberg',
 'woody harrelson',
 'audience intelligence underestimated',
 'cgi',
 'cheesy',
 'comic book',
 'dc',
 'dc comics',
 'ryan reynolds',
 'space',
 'superhero',
 'comedy',
 'funny',
 'happy ending',
 'hot actress',
 'justin timberlake',
 'mila kunis',
 'new york city',
 'romance',
 'sex',
 'istanbul',
 'liam neeson',
 'predictable',
 'turkey',
 'unnecessary sequel',
 'action',
 'christoph waltz',
 'funny',
 'good soundtrack',
 'great performances',
 'humour',
 'leonardo dicaprio',
 'quentin tarantino',
 'samuel l. jackson',
 'soundtrack',
 'western',
 'amy adams',
 'superhero',
 'daniel radcliffe',
 'zoe kazan',
 'comedy',
 'steve carell',
 'stupid but funny',
 'will ferrell',
 'anti-intellectual',
 'bad writing',
 'dystopia',
 'new society',
 'plot holes',
 'predictable',
 'scifi',
 'unintelligent',
 'charlize theron',
 'liam neeson',
 'seth macfarlane',
 'witty',
 'action',
 'dystopia',
 'plot holes',
 'post-apocalyptic',
 'survival',
 'thriller',
 'unexplained',
 'weak plot',
 'dark hero',
 'gun-fu',
 'keanu reeves',
 'revenge',
 'secret society',
 'stylish',
 'black comedy',
 'dark comedy',
 'dark humor',
 'ironic',
 'multiple short stories',
 'short stories',
 'bromance',
 'comedy',
 'funny',
 'james franco',
 'seth rogen',
 'comic book',
 'dr. strange',
 'great villain',
 'guardians of the galaxy',
 'marvel',
 'mcu',
 'robert downey jr.',
 'thanos',
 'thor',
 'visually stunning',
 'characters',
 'dialogue',
 'humor',
 'kurt russell',
 'quentin tarantino',
 'samuel l. jackson',
 'tension building',
 'violent',
 'western',
 'dystopia',
 'jennifer lawrence',
 'love story',
 'nonsense',
 'politics',
 'rebellion',
 'revolution',
 'ben kingsley',
 'ethics',
 'immortality',
 'ryan reynolds',
 'bad story',
 'bad writing',
 'batman',
 'ben affleck',
 'comic book',
 'dc comics',
 'good soundtrack',
 'harley quinn',
 "harley quinn's ass",
 'horrible directing',
 'jared leto',
 'joker',
 'lack of plot',
 'margot robbie',
 'poor story',
 'poorly paced',
 'superhero',
 'visually appealing',
 'will smith',
 'action',
 'batman',
 'ben affleck',
 'dark',
 'dc comics',
 'gal gadot',
 'superhero',
 'superman',
 'wonderwoman',
 'leonardo dicarpio',
 'survival',
 'tom hardy',
 'visually appealing',
 'building a family',
 'creative',
 'freedom',
 'good writing',
 'individualism',
 'viggo mortensen',
 'action',
 'dark hero',
 'gun tactics',
 'hitman',
 'keanu reeves',
 'organized crime',
 'secret society',
 'dystopia',
 'future',
 'interesting',
 'jon hamm',
 'thought provoking',
 'action',
 'comedy',
 'dwayne johnson',
 'funny',
 'comedy',
 'funny',
 'rachel mcadams',
 'adventure',
 'alicia vikander',
 'video game adaptation',
 'josh brolin',
 'ryan reynolds',
 'sarcasm',
 'emilia clarke',
 'star wars',
 'classic',
 'space action',
 'action',
 'sci-fi',
 'epic',
 'great soundtrack',
 'good dialogue',
 'great soundtrack',
 'non-linear',
 'everything you want is here',
 'adventure',
 'classic sci-fi',
 'engrossing adventure',
 'epic',
 'classic',
 'nerd',
 'animation',
 'funny',
 'stone age',
 'action',
 'killer',
 'widows/widowers',
 'animation',
 'kids',
 'robots',
 'action',
 'murder',
 'police',
 'kevin costner',
 'post apocalyptic',
 'dark comedy',
 'dark humor',
 'irreverent',
 'jay and silent bob',
 'kevin smith',
 'satire',
 'irreverent',
 'based on a book',
 'bloody',
 'brutal',
 'controversial',
 'dystopia',
 'goretastic',
 'satire',
 'social commentary',
 'survival',
 'violence',
 'alternate reality',
 'sci-fi',
 'science fiction',
 'time travel',
 'brutal',
 'clever',
 'disturbing',
 'great ending',
 'mindfuck',
 'surprise ending',
 'suspense',
 'cruel characters',
 'brutality',
 'dark humor',
 'threesome',
 'seth rogen',
 'sexual humor',
 'seth rogen',
 'embarassing scenes',
 'offensive',
 'r language',
 'sarcasm',
 'satire',
 "80's",
 'crude humor',
 'mindfuck',
 'sarcasm',
 'satire',
 'vulgar',
 'sofia coppola',
 'john cusack',
 'ewan mcgregor',
 'renee zellweger',
 'jackie chan',
 'kung fu',
 'something for everyone in this one... saw it without and plan on seeing it with kids!',
 'assassin',
 'jean reno',
 'assassin',
 'assassin-in-training (scene)',
 'espionage',
 'robert ludlum',
 'test tag',
 'feel-good',
 'fun family movie',
 'very funny',
 'black and white',
 'christopher nolan',
 'directorial debut',
 'mindfuck',
 'not linear',
 'twist ending',
 'action',
 'comic book',
 'hugh jackman',
 'marvel',
 'superhero',
 'dark',
 'mindfuck',
 'nonlinear',
 'psychology',
 'twist ending',
 'alan rickman',
 'harry potter',
 'humorous',
 'magic',
 'atmospheric',
 'insomnia',
 'thought-provoking',
 'amazing artwork',
 'anime',
 'sci-fi',
 'anime',
 'end of the world',
 'epic',
 'mecha',
 'psychology',
 'anime',
 'comedy',
 'gintama',
 'remaster',
 'classic sci-fi',
 'space action',
 'space epic',
 'atmospheric',
 'cult film',
 'dreamlike',
 'hallucinatory',
 'psychological',
 'surreal',
 'time travel',
 'dreamlike',
 'sentimental',
 'surreal',
 'tim burton',
 'alternate reality',
 'memory',
 'thought-provoking',
 'cinematography',
 'india',
 'surreal',
 'oldie but goodie',
 'sci-fi',
 'star wars',
 'big wave',
 'surfing',
 'ummarti2006',
 'funny',
 'high school',
 'comic book',
 'notable nudity',
 'moldy',
 'old',
 'moving',
 'predictable',
 'a clever chef rat',
 'inspirational',
 'animation',
 'hope',
 'atmospheric',
 'drugs',
 'mathematics',
 'zombies',
 'depressing',
 'stupid',
 'predictable',
 'favelas',
 'black comedy',
 'based on a book',
 'dark comedy',
 'narrated',
 'reciprocal spectator',
 'reciprocal spectator',
 'documentary',
 'animation',
 'documentary',
 'henry darger',
 'the catholic church is the most corrupt organization in history',
 'childish naivity',
 'friendship',
 'adventure',
 'bechdel test:fail',
 'cartoon',
 'children',
 'computer animation',
 'divorce',
 'dogs',
 'dreams',
 'pixar',
 'narrative pisstake',
 'american idolatry',
 'atmospheric',
 'coen brothers',
 'jeff bridges',
 'matt damon',
 'predictable',
 'celebrity fetishism',
 'mediacentralism',
 'system holism',
 'city politics',
 'italy',
 'political right versus left',
 'creature feature',
 'documentary',
 'music industry',
 'remix culture',
 'film history',
 'poetic',
 'representation of children',
 'disney',
 'disney animated feature',
 'oscar (best music - original score)',
 'music',
 'ben stiller',
 'comic book',
 'music',
 'music',
 'awesome',
 'british comedy',
 'pixar',
 'superhero',
 'knights',
 'highschool',
 'cult',
 'boksdrama',
 'stiller',
 'wapendrama',
 'animation',
 'sisters',
 'robots and androids',
 'space',
 'post-college',
 'restaurant',
 'transvestite',
 'satire',
 'dark comedy',
 'chick flick',
 'funny',
 'paul rudd',
 'quotable',
 'seen more than once',
 'amazing cinematography',
 'leonardo dicaprio',
 'shakespeare',
 'updated classics',
 'atmospheric',
 'bruce willis',
 'ghosts',
 'imdb top 250',
 'mindfuck',
 'stylized',
 'twist ending',
 'android(s)/cyborg(s)',
 'artificial intelligence',
 'bittersweet',
 'steven spielberg',
 'cinematography',
 'tom hanks',
 'bette davis',
 'oscar (best actress)',
 'mark ruffalo',
 'clever',
 'high school',
 'lesbian subtext',
 'leonardo dicaprio',
 'suspense',
 'twist ending',
 'undercover cop',
 'christian bale',
 'casey affleck',
 'great performances',
 'twist',
 'ending',
 'anne hathaway',
 'christian bale',
 'christopher nolan',
 'comic book',
 'great ending',
 'morgan freeman',
 'political commentary',
 'superhero',
 'afghanistan',
 'american propaganda',
 'assassination',
 'military',
 'terrorism',
 'time travel',
 'mystery',
 'twist ending',
 'mindfuck',
 'suspense',
 'thriller',
 'tricky',
 'twist ending',
 'addiction',
 'heroin',
 'leonardo dicaprio',
 'mark wahlberg',
 'controversial',
 'new york city',
 'nudity (full frontal)',
 'cynical',
 'hilarious',
 'independent film',
 'quirky',
 'witty',
 'classic sci-fi',
 'sci-fi',
 'space adventure',
 'star wars',
 'brutality',
 'controversial',
 'dark comedy',
 'psychedelic',
 'satire',
 'stylized',
 'cult film',
 'drugs',
 'quentin tarantino',
 'tarantino',
 'soundtrack',
 'thought-provoking',
 'sci-fi',
 'apocalypse',
 'arnold schwarzenegger',
 'nuclear war',
 'sci-fi',
 'suspense',
 'time travel',
 'based on a true story',
 'dark comedy',
 'kidnapping',
 'steve buscemi',
 'edward norton',
 'psychology',
 'suspense',
 'thought-provoking',
 'twist ending',
 'ensemble cast',
 'nonlinear',
 'quentin tarantino',
 'stylized',
 'freedom of expression',
 'british comedy',
 'monty python',
 'emotional',
 'jack nicholson',
 'adventure',
 'archaeology',
 'indiana jones',
 'steven spielberg',
 'treasure hunt',
 'action',
 'aliens',
 'horror',
 'sci-fi',
 'space',
 'space craft',
 'space travel',
 'suspense',
 'alfred hitchcock',
 'psychology',
 'suspenseful',
 'tense',
 'action',
 'artificial intelligence',
 'robots',
 'sci-fi',
 'special effects',
 'tense',
 'time travel',
 'atmospheric',
 'disturbing',
 'horror',
 'jack nicholson',
 'masterpiece',
 'psychological',
 'stanley kubrick',
 'suspense',
 'horror',
 'juliette lewis',
 'martin scorsese',
 'robert de niro',
 'mindfuck',
 'mystery',
 'plot twist',
 'psychological',
 'suspense',
 'twist ending',
 'inspirational',
 'hallucinatory',
 'mental illness',
 'mindfuck',
 'paranoid',
 'ben stiller',
 'crude humor',
 'goofy',
 'atmospheric',
 'creepy',
 'paranoia',
 'scary',
 'suspense',
 'snl',
 'thought-provoking',
 'nicolas cage',
 'martial arts',
 'sci-fi',
 'adult humor',
 'controversial',
 'crude humor',
 'free speech',
 'parody',
 'satire',
 'south park',
 'trey parker',
 'dark comedy',
 'psychology',
 'thought-provoking',
 'twist ending',
 'based on a book',
 'creepy',
 'disturbing',
 'jude law',
 'murder',
 'obsession',
 'psychology',
 'secrets',
 'serial killer',
 'suspense',
 'asylum',
 'based on a true story',
 'brittany murphy',
 'mental hospital',
 'psychology',
 'winona ryder',
 'claustrophobic',
 'horror',
 'scary',
 'stephen king',
 'suspenseful',
 'tense',
 'thriller',
 'aliens',
 'sci-fi',
 'scifi cult',
 'satire',
 'comedy',
 'robert de niro',
 'mystery',
 'psychological',
 'twist ending',
 'al pacino',
 'ben stiller',
 'comedy',
 'david bowie',
 'goofy',
 'mindless one liners',
 'will ferrell',
 'jake gyllenhaal',
 'fantasy',
 'high fantasy',
 'magic',
 'mythology',
 'tolkien',
 'wizards',
 'black and white',
 'samurai',
 'multiple storylines',
 'true story',
 'comedy',
 'will ferrell',
 'rob zombie',
 'jim carrey',
 'comedy',
 'will ferrell',
 'christian bale',
 'creepy',
 'powerful ending',
 'psychology',
 'schizophrenia',
 'twist ending',
 'drugs',
 'lesbian',
 'ben stiller',
 'robert de niro',
 'rob zombie',
 'jake gyllenhaal',
 'modern war',
 'atmospheric',
 'jack nicholson',
 'leonardo dicaprio',
 'martin scorsese',
 'suspense',
 'based on a play',
 'conspiracy theory',
 'creepy',
 'insanity',
 'paranoia',
 'ptsd',
 'funny',
 'will ferrell',
 'claymation',
 'creepy',
 'dark',
 'dark fairy tale',
 'surreal',
 'tim burton',
 'black comedy',
 'brad pitt',
 'christoph waltz',
 'quentin tarantino',
 'satire',
 'insanity',
 'leonardo dicaprio',
 'martin scorsese',
 'plot twist',
 'psychological',
 'psychological thriller',
 'thought-provoking',
 'action',
 'alternate reality',
 'leonardo dicaprio',
 'sci-fi',
 'thought-provoking',
 'visually appealing',
 'stranded',
 'alter ego',
 'atmospheric',
 'creepy',
 'horror',
 'obsession',
 'surreal',
 'illusions',
 'overcomplicated',
 'predictable',
 'stupid ending',
 'absorbing',
 'acting',
 'atmospheric',
 'hugh jackman',
 'jake gyllenhaal',
 'morality',
 'mystery',
 'thriller',
 'jared leto',
 'social commentary',
 'uplifting',
 'fantasy',
 'tolkien',
 'too long',
 'christopher nolan',
 'sci-fi',
 'time-travel',
 'atmospheric',
 'dark',
 'metaphorical',
 'psychological',
 'annoying',
 'stupid ending',
 'dark comedy',
 'dark comedy',
 'psychology',
 'superhero',
 'myth',
 'action',
 'myth',
 'cambodia',
 'crime',
 'human rights',
 'murder',
 'procedural',
 'pixar',
 'game',
 'pregnancy',
 'remake',
 'remake',
 'politics',
 'president',
 'politics',
 'president',
 'mafia',
 'jane austen',
 'hollywood',
 'serial killer',
 'alcoholism',
 'shakespeare',
 'in netflix queue',
 'jane austen',
 'kidnapping',
 'high school',
 ...]

In [5]:
#Using the WordNet Lemmatizer to find out number of unique tags
#Creating a dictionary to map the different variations of the same tag against it's unique name
lemmatizer = WordNetLemmatizer()
f=0

tag_lemmatized = {}
tag_lemmatized_list = []
for x in tag_list:
    lem_word = lemmatizer.lemmatize(x)
    tag_lemmatized_list.append(lem_word)
    if lem_word not in tag_lemmatized :
        tag_lemmatized[lem_word]=[x]
    else :
        tag_lemmatized[lem_word].append(x)

len(tag_lemmatized)

1459

In [6]:
#Storing the unique tag names in a separate list
unique_tag = []
unique_tags = tag_lemmatized.keys()
len(unique_tags)

1459

In [7]:
#Creating a unique tags dataframe and giving each unique tag a unique id
tag_id = []
tag_id = range(1,1460)
unique_tags_df = pd.DataFrame(unique_tags,columns=['tags'])
unique_tags_df['tag_id'] = tag_id
unique_tags_df = unique_tags_df[['tag_id', 'tags']]
unique_tags_df

      tag_id              tags
0          1             funny
1          2   highly quotable
2          3      will ferrell
3          4      boxing story
4          5               mma
...      ...               ...
1454    1455              70mm
1455    1456         for katie
1456    1457           austere
1457    1458            gun fu
1458    1459  heroic bloodshed

[1459 rows x 2 columns]

In [8]:
#Storing the unique tags dataframe into a csv file
unique_tags_df.to_csv('Genome-tags.csv',index=False)

In [9]:
#Replacing the original tags in the csv file with the lemmatized ones
#This removes any discrepancies for later on
tags['tags'] = pd.Series(tag_lemmatized_list)
tags = tags.drop(['tag'],axis=1)
tags.head(10)

   userId  movieId   timestamp               tags
0       2    60756  1445714994              funny
1       2    60756  1445714996    highly quotable
2       2    60756  1445714992       will ferrell
3       2    89774  1445715207       boxing story
4       2    89774  1445715200                mma
5       2    89774  1445715205          tom hardy
6       2   106782  1445715054               drug
7       2   106782  1445715051  leonardo dicaprio
8       2   106782  1445715056    martin scorsese
9       7    48516  1169687325       way too long

In [10]:
#Merging the tags dataframe with the unique tags dataframe to get the corresponding tag ids
tags_with_ids = pd.merge(tags,unique_tags_df,on='tags')
tags_with_ids

      userId  movieId   timestamp              tags  tag_id
0          2    60756  1445714994             funny       1
1         62     2953  1525636885             funny       1
2         62     3114  1525636913             funny       1
3         62    60756  1528934381             funny       1
4         62    68848  1527274322             funny       1
...      ...      ...         ...               ...     ...
3678     606     7382  1171234019         for katie    1456
3679     606     7936  1173392334           austere    1457
3680     610     3265  1493843984            gun fu    1458
3681     610     3265  1493843978  heroic bloodshed    1459
3682     610   168248  1493844270  heroic bloodshed    1459

[3683 rows x 5 columns]

In [12]:
#Dropping the timestamp column
tags_with_ids = tags_with_ids.drop(['timestamp'], axis=1)
tags_with_ids

      userId  movieId              tags  tag_id
0          2    60756             funny       1
1         62     2953             funny       1
2         62     3114             funny       1
3         62    60756             funny       1
4         62    68848             funny       1
...      ...      ...               ...     ...
3678     606     7382         for katie    1456
3679     606     7936           austere    1457
3680     610     3265            gun fu    1458
3681     610     3265  heroic bloodshed    1459
3682     610   168248  heroic bloodshed    1459

[3683 rows x 4 columns]

In [13]:
#Dropping the tag names
tags_with_ids = tags_with_ids.drop(['tags'], axis=1)
tags_with_ids

      userId  movieId  tag_id
0          2    60756       1
1         62     2953       1
2         62     3114       1
3         62    60756       1
4         62    68848       1
...      ...      ...     ...
3678     606     7382    1456
3679     606     7936    1457
3680     610     3265    1458
3681     610     3265    1459
3682     610   168248    1459

[3683 rows x 3 columns]

In [14]:
#Storing the tags with ids dataframe into a csv file
tags_with_ids.to_csv('Tags_IDs.csv', index=False)